"""Data-source strategy and adapter contracts."""

from cogalpha.data_sources.qlib_direct import (
    DirectQlibExportConfig,
    DirectQlibProbeResult,
    DirectQlibSourceManifest,
    QlibAdjustmentEvidence,
    QlibBenchmarkReturnEvidence,
    QlibCalendarEvidence,
    QlibEnvironmentStatus,
    build_direct_qlib_source_manifest,
    build_hf_fallback_evidence,
    check_direct_qlib_environment,
    extract_qlib_ohlcv_panel,
    load_direct_qlib_source_manifest_json,
    load_sh000300_benchmark_returns,
    probe_direct_qlib_source,
    render_direct_qlib_source_manifest_markdown,
    write_benchmark_returns_manifest_json,
    write_direct_qlib_source_manifest_json,
    write_direct_qlib_source_manifest_markdown,
)
from cogalpha.data_sources.strategy import (
    DataSourceCandidateAssessment,
    DataSourcePathId,
    DataSourceRole,
    Phase13DataStrategyDecision,
    Phase13FallbackRule,
    build_phase13_data_strategy_decision,
    load_phase13_data_strategy_json,
    render_phase13_data_strategy_markdown,
    write_phase13_data_strategy_json,
    write_phase13_data_strategy_markdown,
)

__all__ = [
    "DataSourceCandidateAssessment",
    "DataSourcePathId",
    "DataSourceRole",
    "DirectQlibExportConfig",
    "DirectQlibProbeResult",
    "DirectQlibSourceManifest",
    "Phase13DataStrategyDecision",
    "Phase13FallbackRule",
    "QlibAdjustmentEvidence",
    "QlibBenchmarkReturnEvidence",
    "QlibCalendarEvidence",
    "QlibEnvironmentStatus",
    "build_direct_qlib_source_manifest",
    "build_phase13_data_strategy_decision",
    "build_hf_fallback_evidence",
    "check_direct_qlib_environment",
    "extract_qlib_ohlcv_panel",
    "load_direct_qlib_source_manifest_json",
    "load_phase13_data_strategy_json",
    "load_sh000300_benchmark_returns",
    "probe_direct_qlib_source",
    "render_direct_qlib_source_manifest_markdown",
    "render_phase13_data_strategy_markdown",
    "write_benchmark_returns_manifest_json",
    "write_direct_qlib_source_manifest_json",
    "write_direct_qlib_source_manifest_markdown",
    "write_phase13_data_strategy_json",
    "write_phase13_data_strategy_markdown",
]
